CC = c++ -O2 -falign-functions=4
OBJOPT = -o 
OUTOPT = -o 
LD = c++ -shared -falign-functions=4
EXELD = c++ -falign-functions=4
SOFLAGS = 
EXESFX = .exe
LSFX = dll
LPFX = lib
LIBS = -L$(ARCHDIR) -lRAPID
