CC = c++ -O2 -falign-functions=8 -fPIC 
OBJOPT = -o 
OUTOPT = -o 
LD = c++
SOFLAGS = -dynamiclib -flat_namespace -undefined suppress
EXELD = c++
EXESFX = 
LSFX = so
LPFX = lib
LIBS = -L$(ARCHDIR) -lRAPID 
